### ISSUE TITLE
似乎某些组件的生命周期与React有所不同

### ISSUE THREAD

**Issue by otakustay** [YMFE/qreact#4]
时间有限，暂时没有找到根源，贴2个图：

- React的效果：

    <img width="357" alt="jietu20170921-173104 2x" src="https://user-images.githubusercontent.com/639549/30689172-d13d102e-9e85-11e7-8e71-ec3666a0d6da.png">

- QReact的效果：

    <img width="631" alt="jietu20170921-172948 2x" src="https://user-images.githubusercontent.com/639549/30689186-dcca2760-9e85-11e7-91d1-70eef82bdf32.png">

错误的起因是connect的时候`mapStateToProps`有异常，因此connect组件`render`时就会抛出，但是在React下，connect组件被unmount以后就不会再渲染所以没出现异常，而qreact下又进行了一次渲染

后续有时间了我会继续研究下，当然你们能这样就知道是啥问题最好了

**Comment by RubyLouvre** [comment]
有例子就最好了

**Comment by huang-x-h** [comment]
@RubyLouvre 这个和 `anu` 貌似重复了

**Comment by RubyLouvre** [comment]
@huang-x-h 因为都是我搞的

**Comment by otakustay** [comment]
已经确认问题，组件在`componentWillUnmount`中调用`setState`的话，在已经unmount的状态下依旧会触发`render`，有可能是`setStateImpl`没有检查组件的状态

另外一个题外话，为啥`debounceSetState`用了300ms的`setTimeout`，虽然我肯定不会在`didUpdate`之类的地方用`setState`吧，不过会不会有一个再短一点又不会卡死的值？

以下为可复现问题的代码：

```jsx
import {PureComponent} from 'react';
import {render} from 'react-dom';

class Issue extends PureComponent {
    state = {
        status: 'normal'
    };

    componentWillUnmount() {
        this.setState({status: 'unmount'})
    }

    render() {
        const {status} = this.state;

        if (status === 'unmount') {
            throw new Error('Issue unmounted');
        }

        return <span>Issue status: {status}</span>
    }
}

class App extends PureComponent {
    state = {
        showIssue: true
    };

    render() {
        const {showIssue} = this.state;

        return (
            <div>
                {showIssue && <Issue />}
                <button type="button" onClick={() => this.setState({showIssue: !showIssue})}>Click</button>
            </div>
        )
    }
}

render(
    <App />,
    document.body.appendChild(document.createElement('div'))
);
```

**Comment by RubyLouvre** [comment]
那我在用户调用componentWillUnmount前，将setState,forceUpdate替换成空函数吧

**Comment by otakustay** [comment]
我觉得不合适，如果`setState`的参数是一个函数，且这个函数有副作用，那么你就会与React不一样了，虽然是开发者作的死

我建议还是在render的时候判断下`isMount`之类的状态吧

**Comment by RubyLouvre** [comment]
```javascript
       componentWillUnmount() {
            this.setState({},function(){
              console.log('===============')
            })
        }
    
```
 或
```javascript
       componentWillUnmount() {
            this.setState(function(){
              console.log('===============')
            })
        }
    
```
在官方React也什么日志没打出来

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/anu/blob/master/src/dispose.js#L42-L52

详看这里，下周发个新版本

**Comment by otakustay** [comment]
good，很好~
